import type { Metadata } from "next";
import { Provider } from 'jotai'
import { Geist, Geist_Mono } from "next/font/google"
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen overflow-hidden`}
      >
       <div className="flex flex-col h-full w-full">
         <TRPCReactProvider>
          <NuqsAdapter>
            <Provider>
            {children}
          <Toaster/>
          </Provider>
           </NuqsAdapter>
         </TRPCReactProvider>
       </div>
      </body>
    </html>
  );
}
